config/routes.rb
Rails.application.routes.draw do
  get 'activities/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#top"
  get 'search' => 'homes#search'
  resources :items
  resources :activities
end

app/models/activity.rb
class Activity < ApplicationRecord
    has_many :relations
    has_many :items , through: :relations
    def self.search(keyword)
    where(["name like?", "%#{keyword}%"])
    end

    def self.transpotation(boolean)
    where(["transpotation like?", "%#{boolean}%"])
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :relations, dependent: :destroy
  has_many :activities , through: :relations
  accepts_nested_attributes_for :relations, allow_destroy: true


end

app/models/relation.rb
class Relation < ApplicationRecord
  belongs_to :activity ,optional: true
  belongs_to :item
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def new
    @activity = Activity.new
    @activities = Activity.all
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.save
    redirect_to root_path
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])
    @activity.update(activity_params)
    redirect_to activity_path(@activity.id)
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to root_path
  end

  private
    def  activity_params
      params.require(:activity).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @activity = Activity.all
  end


  def search
    # @items = Activity.joins(:items,:relations).search()
    @activity = Activity.search(params[:keyword])
    @keyword = params[:keyword]
    # binding.pry
    render "top"
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @relations = @item.relations.build ##親モデル.子モデル.buildで子モデルのインスタンス作成
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to item_path(@item.id)

  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to item_path(@item.id), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
  end


  private
    def  item_params
      params.require(:item).permit(:name, :season, :amenity, :toransportation ,:_destroy,
      relations_attributes: [:id, :item_id, :activity_id ,:_destroy]
      )

    end


end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/activities/edit.html.erb
アクティビティ編集
<%= form_with model:@activity, local: true do |f| %>
種類
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

<%= link_to '削除' ,activity_path(@activity.id) ,method: :delete, data: {confirm:'本当に削除しますか？'} %>

app/views/activities/new.html.erb
新しく持ちものを追加する
<%= form_with model:@activity, local: true do |f| %>
種類
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

<% @activities.each do |activity| %>
  <%= link_to activity.name ,activity_path(activity.id) %>
<% end %>

app/views/activities/show.html.erb
<%= @activity.name %>
<%= link_to "編集" , edit_activity_path(@activity.id) %>

app/views/homes/_item.html.erb
  <% @activity.each do |activity| %>
      <% activity.relations.each do |relation| %>
        <%= relation.item.name %>
      <% end %>
  <% end %>

app/views/homes/top.html.erb
  <%= form_with url: search_path, method: :get, local: true do |f| %>

<span class="start">開始</span>
<div class="top-form">
<div class="top-form_season">
  saesonは？
  <span class="top-form_season_btn">春</span>
  <span class="top-form_season_btn">夏</span>
  <span class="top-form_season_btn">秋</span>
  <span class="top-form_season_btn">冬</span>
  <span class="top-form_season_btn">年中</span>
</div>

<div class="top-form_amenity">
  amenityは？(いる/いらない)
    <span class="top-form_amenity_btn">いる</span>
    <span class="top-form_amenity_btn">いらない</span>
</div>


<div class="top-form_transpotation">
  transpotationは？(乗り物を使う/いらない)
  <span class="top-form_transpotation_btn">使う</span>
  <input value="true" type="hidden" name="boolean" id="boolean" />
  <span class="top-form_transpotation_btn">いらない</span>
</div>

<div class="top-form_activity_1">
  activityは？
  <span class="top-form_activity_1_1_btn">山</span>
  <span class="top-form_activity_1_2_btn">海</span>
  <span class="top-form_activity_1_3_btn">その他</span>
</div>

  <div class="top-form_activity_2_1">
    <span class="top-form_activity_2_btn top-form_activity_2_1_1">登山</span>
    <span class="top-form_activity_2_btn top-form_activity_2_1_2">キャンプ</span>
    <span class="top-form_activity_2_btn top-form_activity_2_1_3">川遊び</span>
  </div>

  <div class="top-form_activity_2_2">
    <span class="top-form_activity_2_btn top-form_activity_2_2_1">釣り</span>
    <span class="top-form_activity_2_btn top-form_activity_2_2_2">海水浴</span>
    <span class="top-form_activity_2_btn top-form_activity_2_2_3">ダイビング</span>
  </div>

  <div class="top-form_activity_2_3">
    <span class="top-form_activity_2_btn top-form_activity_2_3_1">遊園地</span>
    <span class="top-form_activity_2_btn top-form_activity_2_3_2">ドライブ</span>
    <span class="top-form_activity_2_btn top-form_activity_2_3_3">自転車旅</span>
  </div>


<span class="seach"><%= f.submit '検索' %></span>
</div>
<% end %>

<% if @activity != Activity.all %>
  <%= render "item" %>
<% end %>

app/views/items/_form.html.erb
<%= form_with(model: @item, local: true) do |s| %>
名前
  <%= s.text_field :name %>
季節
  <%= s.select :season, ['春', '夏', '秋', '冬','通年'], {include_blank: '選択してください'} %>
移動方法
      <%= s.radio_button :toransportation, true %>
      <%= s.label :toransportation, '電車/新幹線/', value: true ,checked: true%>

      <%= s.radio_button :toransportation, false %>
      <%= s.label :toransportation, 'なし', value: false %>

アメニティ
      <%= s.radio_button :amenity, true %>
      <%= s.label :amenity, 'あり', value: true ,checked: true%>

      <%= s.radio_button :amenity, false %>
      <%= s.label :amenity, 'なし', value: false %>
    <%= s.fields_for :relations do |t| %>
      <%= render "relation_fields", f: t %>
    <% end %>
      <div class="links">
        <span><%= link_to_add_association "追加", s, :relations %></span>
      </div>

   <%= s.submit %>
<% end %>

app/views/items/_relation_fields.html.erb
<div class="nested-fields cooking_from">


  <div class="meals-new_table_row">

    <%= f.hidden_field :item_id %>
    <%= f.collection_select :activity_id, Activity.all, :id, :name ,:include_blank => "選択してください" %>
  </div>
  <div><%= link_to_remove_association '削除', f, class: 'meals-new_table_delete_btn_cooking' %></div>
</div>

app/views/items/edit.html.erb
新しく持ちものを追加する
<h1>New Project</h1>
<%= render 'form', item: @item %>
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<% @items.each do |item| %>
  <%= link_to item.name , edit_item_path(item.id) %>
<% end %>

app/views/items/new.html.erb
新しく持ちものを登録する
<%= render 'form', item: @item %>
<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<%= @item.name %>
<%= @item.season %>
<%= @item.amenity %>
<%= @item.toransportation %>

    <% @item.relations.each do |relation| %>
      <% if  relation.activity.present?  %>
      <%= relation.activity.name %>
      <% end %>
    <% end %>

<%= link_to '編集', edit_item_path(@item.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BelongingsWeb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= link_to "トップ" , root_path %>
      <%= link_to "持ち物作成" , new_item_path %>
      <%= link_to "アクティビティ作成" , new_activity_path %>
      <%= link_to "持ち物一覧", items_path %>
    </header>
    <%= yield %>
  </body>
</html>